version: '3.4'

services:

  redis:
    container_name: "dapr_redis" 
    image: redis:alpine
    hostname: bankstate
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"

  dapr-placement:
    image: "daprio/dapr:1.0.0"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  cashmachine:
    image: ${DOCKER_REGISTRY-}cashmachine
    build:
      context: .
      dockerfile: CashMachine/Dockerfile
    ports:
      - "50001:50001"

  cashmachine-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "cashmachine", "-app-port", "80", "-components-path", "/components", ]
    depends_on:
      - cashmachine
    network_mode: "service:cashmachine"
    volumes:
      - "./dapr/components/:/components"

  bankbackend:
    image: ${DOCKER_REGISTRY-}bankbackend
    build:
      context: .
      dockerfile: BankBackend/Dockerfile
    ports:
      - "50002:50001"

  bankbackend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "bankbackend", "-app-port", "80" , "-components-path", "/components", "-placement-host-address", "dapr-placement:50000",]
    depends_on:
      - bankbackend
    network_mode: "service:bankbackend"
    volumes:
      - "./dapr/components/:/components"

  transactionmonitor:
    image: ${DOCKER_REGISTRY-}transactionmonitor
    build:
      context: .
      dockerfile: TransactionMonitor/Dockerfile
    ports:
      - "50003:50001"

  transactionmonitor-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "transactionmonitor", "-app-port", "80" , "-components-path", "/components", ]
    depends_on:
      - transactionmonitor
    network_mode: "service:transactionmonitor"
    volumes:
      - "./dapr/components/:/components"