version: '3.4'

services:
  bankbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  cashmachine:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  transactionmonitor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

